# Generated by Django 5.2.15 on 2026-06-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Haldi', 'Haldi'), ('school Function', 'school Function'), ('Birthday', 'Birthday'), ('Garba', 'Garba'), ('Corporate', 'Corporate'), ('DJ Night', 'DJ Night'), ('Barat on wheels', 'Barat on wheels'), ('Other', 'Other')], max_length=50, unique=True),
        ),
    ]
