# Generated by Django 5.2.15 on 2026-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_description_remove_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Haldi', 'Haldi'), ('school Function', 'school Function'), ('Birthday', 'Birthday'), ('Garba', 'Garba'), ('Corporate', 'Corporate'), ('DJ Night', 'DJ Night'), ('Barat on wheels', 'Barat on wheels'), ('Other', 'Other')], max_length=50),
        ),
    ]
