# Generated by Django 5.2.15 on 2026-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_name_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Haldi', 'Haldi'), ('school Function', 'school Function'), ('Birthday', 'Birthday'), ('Garba', 'Garba'), ('Navratri', 'Navratri'), ('Bhajan', 'Bhajan'), ('Corporate', 'Corporate'), ('DJ Night', 'DJ Night'), ('Barat on wheels', 'Barat on wheels'), ('Other', 'Other')], max_length=50),
        ),
    ]
