# Generated by Django 5.2.15 on 2026-06-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_name_alter_event_event_type'),
        ('expenses', '0002_expense_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Chai Nasto', 'Chai Nasto'), ('Transport', 'Transport'), ('Worker Food', 'Worker Food'), ('Other', 'Other')], max_length=50),
        ),
    ]
