# Generated by Django 5.2.15 on 2026-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_event_date_booking_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_sound_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sound_type',
            field=models.CharField(choices=[('2-Way', '2-Way'), ('3-Way', '3-Way'), ('Custom', 'Custom')], default='2-Way', max_length=20),
            preserve_default=False,
        ),
    ]
