# Generated by Django 5.2.15 on 2026-06-25 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sound_type',
            field=models.CharField(choices=[('2-Way', '2-Way'), ('3-Way', '3-Way'), ('4-Way', '4-Way'), ('Custom', 'Custom')], max_length=20),
        ),
    ]
