# Generated by Django 5.2.15 on 2026-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_created_at_booking_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dholi',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='timing',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Full Day', 'Full Day')], default='Morning', max_length=20),
        ),
    ]
