# Generated by Django 5.2.15 on 2026-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_dholi_booking_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_dholi_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dholi',
            field=models.CharField(choices=[('No', 'No Dhol'), ('2 Dhol', '2 Dhol'), ('4 Dhol', '4 Dhol'), ('6 Dhol', '6 Dhol'), ('8 Dhol', '8 Dhol'), ('Custom', 'Custom')], default='No', max_length=20),
        ),
    ]
