# Generated by Django 5.2.15 on 2026-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_custom_dholi_count_alter_booking_dholi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dholi',
            field=models.CharField(choices=[('No', 'No Dholi'), ('2 Dholi', '2 Dholi'), ('4 Dholi', '4 Dholi'), ('6 Dholi', '6 Dholi'), ('8 Dholi', '8 Dholi'), ('Custom', 'Custom')], default='No', max_length=20),
        ),
    ]
