# Generated by Django 5.2.15 on 2026-06-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0003_event_event_name_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
